# Advanced Prediction

In [1]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df1 = pd.read_csv("train.csv")
df2 = pd.read_csv("test.csv")

In [3]:
df1.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
df1.shape

(1460, 81)

In [5]:
df2.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [6]:
df2.shape

(1459, 80)

In [7]:
df = df1.append(df2)

In [8]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [9]:
df.shape

(2919, 81)

In [10]:
df.select_dtypes("object").columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [11]:
df = df[['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition',"SalePrice","OverallQual","GrLivArea","GarageCars","GarageArea","TotalBsmtSF","1stFlrSF","FullBath","TotRmsAbvGrd","YearBuilt","YearRemodAdd","GarageYrBlt","MasVnrArea","Fireplaces","BsmtFinSF1","LotFrontage","WoodDeckSF","2ndFlrSF","OpenPorchSF","HalfBath"]]

In [12]:
df = df.drop(columns=["Utilities"])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 62 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       2915 non-null   object
 1   Street         2919 non-null   object
 2   Alley          198 non-null    object
 3   LotShape       2919 non-null   object
 4   LandContour    2919 non-null   object
 5   LotConfig      2919 non-null   object
 6   LandSlope      2919 non-null   object
 7   Neighborhood   2919 non-null   object
 8   Condition1     2919 non-null   object
 9   Condition2     2919 non-null   object
 10  BldgType       2919 non-null   object
 11  HouseStyle     2919 non-null   object
 12  RoofStyle      2919 non-null   object
 13  RoofMatl       2919 non-null   object
 14  Exterior1st    2918 non-null   object
 15  Exterior2nd    2918 non-null   object
 16  MasVnrType     2895 non-null   object
 17  ExterQual      2919 non-null   object
 18  ExterCond      2919 non-null   object
 19  Foundation     2919 non-null   object
 20  BsmtQual       2838 non-null   object
 21  BsmtCond       2837 non-null   object
 22  BsmtExposure   2837 non-null   object
 23  BsmtFinType1   2840 non-null   object
 24  BsmtFinType2   2839 non-null   object
 25  Heating        2919 non-null   object
 26  HeatingQC      2919 non-null   object
 27  CentralAir     2919 non-null   object
 28  Electrical     2918 non-null   object
 29  KitchenQual    2918 non-null   object
 30  Functional     2917 non-null   object
 31  FireplaceQu    1499 non-null   object
 32  GarageType     2762 non-null   object
 33  GarageFinish   2760 non-null   object
 34  GarageQual     2760 non-null   object
 35  GarageCond     2760 non-null   object
 36  PavedDrive     2919 non-null   object
 37  PoolQC         10 non-null     object
 38  Fence          571 non-null    object
 39  MiscFeature    105 non-null    object
 40  SaleType       2918 non-null   object
 41  SaleCondition  2919 non-null   object
 42  SalePrice      1460 non-null   float64
 43  OverallQual    2919 non-null   int64
 44  GrLivArea      2919 non-null   int64
 45  GarageCars     2918 non-null   float64
 46  GarageArea     2918 non-null   float64
 47  TotalBsmtSF    2918 non-null   float64
 48  1stFlrSF       2919 non-null   int64
 49  FullBath       2919 non-null   int64
 50  TotRmsAbvGrd   2919 non-null   int64
 51  YearBuilt      2919 non-null   int64
 52  YearRemodAdd   2919 non-null   int64
 53  GarageYrBlt    2760 non-null   float64
 54  MasVnrArea     2896 non-null   float64
 55  Fireplaces     2919 non-null   int64
 56  BsmtFinSF1     2918 non-null   float64
 57  LotFrontage    2433 non-null   float64
 58  WoodDeckSF     2919 non-null   int64
 59  2ndFlrSF       2919 non-null   int64
 60  OpenPorchSF    2919 non-null   int64
 61  HalfBath       2919 non-null   int64
dtypes: float64(8), int64(12), object(42)
memory usage: 1.4+ MB

In [14]:
df.head()

,MSZoning,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,YearRemodAdd,GarageYrBlt,MasVnrArea,Fireplaces,BsmtFinSF1,LotFrontage,WoodDeckSF,2ndFlrSF,OpenPorchSF,HalfBath
0,RL,Pave,NaN,Reg,Lvl,Inside,Gtl,CollgCr,Norm,Norm,...,2003,2003.0,196.0,0,706.0,65.0,0,854,61,1
1,RL,Pave,NaN,Reg,Lvl,FR2,Gtl,Veenker,Feedr,Norm,...,1976,1976.0,0.0,1,978.0,80.0,298,0,0,0
2,RL,Pave,NaN,IR1,Lvl,Inside,Gtl,CollgCr,Norm,Norm,...,2002,2001.0,162.0,1,486.0,68.0,0,866,42,1
3,RL,Pave,NaN,IR1,Lvl,Corner,Gtl,Crawfor,Norm,Norm,...,1970,1998.0,0.0,1,216.0,60.0,0,756,35,0
4,RL,Pave,NaN,IR1,Lvl,FR2,Gtl,NoRidge,Norm,Norm,...,2000,2000.0,350.0,1,655.0,84.0,192,1053,84,1

In [15]:
#df_dummies = pd.get_dummies(df_new,drop_first=True)

In [16]:
df["MasVnrArea"].fillna(df["MasVnrArea"].mean(),inplace=True)

In [17]:
df["GarageYrBlt"].fillna(0,inplace=True)

In [18]:
df["MSZoning"].fillna("RL",inplace=True)

In [19]:
df["Exterior1st"].fillna("VinylSd",inplace=True)

In [20]:
df["Exterior2nd"].fillna("VinylSd",inplace=True)

In [21]:
df["MasVnrType"].fillna("None",inplace=True)

In [22]:
df["BsmtQual"].fillna("None",inplace=True,limit=40)

In [23]:
df["BsmtCond"].fillna("None",inplace=True)

In [24]:
df["BsmtExposure"].fillna("None",inplace=True,limit=62)

In [25]:
df["BsmtFinType1"].fillna("None",inplace=True,limit=40)

In [26]:
df["BsmtFinType2"].fillna("None",inplace=True)

In [27]:
df["Electrical"].fillna("SBrkr",inplace=True)

In [28]:
df["KitchenQual"].fillna("TA",inplace=True)

In [29]:
df["Functional"].fillna("Typ",inplace=True)

In [30]:
df["SaleType"].fillna("WD",inplace=True)

In [31]:
df["BsmtFinSF1"].fillna(0.0,inplace=True)

In [32]:
df["TotalBsmtSF"].fillna(0.0,inplace=True)

In [33]:
df["GarageCars"].fillna(0.0,inplace=True)

In [34]:
df["GarageArea"].fillna(0.0,inplace=True)

In [35]:
df["GarageType"].fillna("None",inplace=True)

In [36]:
df["GarageFinish"].fillna("None",inplace=True,limit=90)

In [37]:
df["GarageFinish"].fillna("RFn",inplace=True,limit=69)

In [38]:
df["GarageQual"].fillna("None",inplace=True)

In [39]:
df["GarageCond"].fillna("None",inplace=True)

In [40]:
df["PoolQC"].fillna("None",inplace=True)

In [41]:
df["MiscFeature"].fillna("None",inplace=True)

In [42]:
df["Alley"].fillna("None",inplace=True)

In [43]:
df["FireplaceQu"].fillna("None",inplace=True)

In [44]:
df["Fence"].fillna("None",inplace=True)

In [45]:
df["LotFrontage"].fillna(65,inplace=True)

In [46]:
df["GarageType"].value_counts()

Attchd     1723
Detchd      779
BuiltIn     186
None        157
Basment      36
2Types       23
CarPort      15
Name: GarageType, dtype: int64

In [47]:
df.isnull().sum()

MSZoning       0
Street         0
Alley          0
LotShape       0
LandContour    0
              ..
LotFrontage    0
WoodDeckSF     0
2ndFlrSF       0
OpenPorchSF    0
HalfBath       0
Length: 62, dtype: int64

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 62 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       2919 non-null   object
 1   Street         2919 non-null   object
 2   Alley          2919 non-null   object
 3   LotShape       2919 non-null   object
 4   LandContour    2919 non-null   object
 5   LotConfig      2919 non-null   object
 6   LandSlope      2919 non-null   object
 7   Neighborhood   2919 non-null   object
 8   Condition1     2919 non-null   object
 9   Condition2     2919 non-null   object
 10  BldgType       2919 non-null   object
 11  HouseStyle     2919 non-null   object
 12  RoofStyle      2919 non-null   object
 13  RoofMatl       2919 non-null   object
 14  Exterior1st    2919 non-null   object
 15  Exterior2nd    2919 non-null   object
 16  MasVnrType     2919 non-null   object
 17  ExterQual      2919 non-null   object
 18  ExterCond      2919 non-null   object
 19  Foundation     2919 non-null   object
 20  BsmtQual       2878 non-null   object
 21  BsmtCond       2919 non-null   object
 22  BsmtExposure   2899 non-null   object
 23  BsmtFinType1   2880 non-null   object
 24  BsmtFinType2   2919 non-null   object
 25  Heating        2919 non-null   object
 26  HeatingQC      2919 non-null   object
 27  CentralAir     2919 non-null   object
 28  Electrical     2919 non-null   object
 29  KitchenQual    2919 non-null   object
 30  Functional     2919 non-null   object
 31  FireplaceQu    2919 non-null   object
 32  GarageType     2919 non-null   object
 33  GarageFinish   2919 non-null   object
 34  GarageQual     2919 non-null   object
 35  GarageCond     2919 non-null   object
 36  PavedDrive     2919 non-null   object
 37  PoolQC         2919 non-null   object
 38  Fence          2919 non-null   object
 39  MiscFeature    2919 non-null   object
 40  SaleType       2919 non-null   object
 41  SaleCondition  2919 non-null   object
 42  SalePrice      1460 non-null   float64
 43  OverallQual    2919 non-null   int64
 44  GrLivArea      2919 non-null   int64
 45  GarageCars     2919 non-null   float64
 46  GarageArea     2919 non-null   float64
 47  TotalBsmtSF    2919 non-null   float64
 48  1stFlrSF       2919 non-null   int64
 49  FullBath       2919 non-null   int64
 50  TotRmsAbvGrd   2919 non-null   int64
 51  YearBuilt      2919 non-null   int64
 52  YearRemodAdd   2919 non-null   int64
 53  GarageYrBlt    2919 non-null   float64
 54  MasVnrArea     2919 non-null   float64
 55  Fireplaces     2919 non-null   int64
 56  BsmtFinSF1     2919 non-null   float64
 57  LotFrontage    2919 non-null   float64
 58  WoodDeckSF     2919 non-null   int64
 59  2ndFlrSF       2919 non-null   int64
 60  OpenPorchSF    2919 non-null   int64
 61  HalfBath       2919 non-null   int64
dtypes: float64(8), int64(12), object(42)
memory usage: 1.4+ MB

# DÃ¼zenleme

In [49]:
df = df[df["LotFrontage"]<150]
df["YearBuilt"] = 2022-df["YearBuilt"]
df["YearRemodAdd"] = 2022-df["YearRemodAdd"]
df = df[df["GrLivArea"]<3000]
df = df[df["GarageCars"]<4]
df = df[df["GarageArea"]<1000]
df = df[df["TotalBsmtSF"]<3000]
df = df[df["1stFlrSF"]<3000]
df = df[df["TotRmsAbvGrd"]<11]
df["GarageYrBlt"] = 2022-df["GarageYrBlt"]
df = df[df["GarageYrBlt"]>0]
df = df[df["Fireplaces"]<3]
df = df[df["BsmtFinSF1"]<2000]
df = df[df["WoodDeckSF"]<=400]
df = df[df["2ndFlrSF"]<1500]
df = df[df["OpenPorchSF"]<300]

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2700 entries, 0 to 1458
Data columns (total 62 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       2700 non-null   object
 1   Street         2700 non-null   object
 2   Alley          2700 non-null   object
 3   LotShape       2700 non-null   object
 4   LandContour    2700 non-null   object
 5   LotConfig      2700 non-null   object
 6   LandSlope      2700 non-null   object
 7   Neighborhood   2700 non-null   object
 8   Condition1     2700 non-null   object
 9   Condition2     2700 non-null   object
 10  BldgType       2700 non-null   object
 11  HouseStyle     2700 non-null   object
 12  RoofStyle      2700 non-null   object
 13  RoofMatl       2700 non-null   object
 14  Exterior1st    2700 non-null   object
 15  Exterior2nd    2700 non-null   object
 16  MasVnrType     2700 non-null   object
 17  ExterQual      2700 non-null   object
 18  ExterCond      2700 non-null   object
 19  Foundation     2700 non-null   object
 20  BsmtQual       2662 non-null   object
 21  BsmtCond       2700 non-null   object
 22  BsmtExposure   2682 non-null   object
 23  BsmtFinType1   2664 non-null   object
 24  BsmtFinType2   2700 non-null   object
 25  Heating        2700 non-null   object
 26  HeatingQC      2700 non-null   object
 27  CentralAir     2700 non-null   object
 28  Electrical     2700 non-null   object
 29  KitchenQual    2700 non-null   object
 30  Functional     2700 non-null   object
 31  FireplaceQu    2700 non-null   object
 32  GarageType     2700 non-null   object
 33  GarageFinish   2700 non-null   object
 34  GarageQual     2700 non-null   object
 35  GarageCond     2700 non-null   object
 36  PavedDrive     2700 non-null   object
 37  PoolQC         2700 non-null   object
 38  Fence          2700 non-null   object
 39  MiscFeature    2700 non-null   object
 40  SaleType       2700 non-null   object
 41  SaleCondition  2700 non-null   object
 42  SalePrice      1349 non-null   float64
 43  OverallQual    2700 non-null   int64
 44  GrLivArea      2700 non-null   int64
 45  GarageCars     2700 non-null   float64
 46  GarageArea     2700 non-null   float64
 47  TotalBsmtSF    2700 non-null   float64
 48  1stFlrSF       2700 non-null   int64
 49  FullBath       2700 non-null   int64
 50  TotRmsAbvGrd   2700 non-null   int64
 51  YearBuilt      2700 non-null   int64
 52  YearRemodAdd   2700 non-null   int64
 53  GarageYrBlt    2700 non-null   float64
 54  MasVnrArea     2700 non-null   float64
 55  Fireplaces     2700 non-null   int64
 56  BsmtFinSF1     2700 non-null   float64
 57  LotFrontage    2700 non-null   float64
 58  WoodDeckSF     2700 non-null   int64
 59  2ndFlrSF       2700 non-null   int64
 60  OpenPorchSF    2700 non-null   int64
 61  HalfBath       2700 non-null   int64
dtypes: float64(8), int64(12), object(42)
memory usage: 1.3+ MB

In [54]:
df["SalePrice"].head()

0    208500.0
1    181500.0
2    223500.0
3    140000.0
4    250000.0
Name: SalePrice, dtype: float64

In [70]:
dfx = df[:1349]

In [67]:
y = df["SalePrice"][:1349]

In [72]:
dfx = dfx.drop(columns=['SalePrice'])

In [73]:
dfx = pd.get_dummies(dfx,drop_first=True)

In [74]:
dfx.shape , y.shape

((1349, 235), (1349,))

In [75]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', 100)

#Regression
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge,Lasso
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import ExtraTreeRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.preprocessing import normalize,scale

In [76]:
def regression_(x,y):
    
    lr = LinearRegression()
    r = Ridge()
    l = Lasso()
    e = ElasticNet()
    kn = KNeighborsRegressor()
    ext = ExtraTreeRegressor()
    gb = GradientBoostingRegressor()
    dt = DecisionTreeRegressor()
    xgb = XGBRegressor()
       
    algos = [lr,r,l,e,kn,ext,gb,dt,xgb]
    algos_names = ['LinearRegressor','Ridge','Lasso','ElasticNet','KNeighbors','ExtraTree','GradientBoosting','DecisionTree','XGB']
    
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = .2, random_state = 42)
    
    r_score = []
    mse = []
    mae = []
    
    result = pd.DataFrame(columns=['R_square','MSE','MAE'],index = algos_names)
    
    for algo in algos:
        pred = algo.fit(x,y).predict(x)
        r_score.append(r2_score(y,pred))
        mse.append(mean_squared_error(y,pred)**.5)
        mae.append(mean_absolute_error(y,pred))
    
    
    result.R_square=r_score
    result.MSE=mse
    result.MAE=mae
    
    return result.sort_values('R_square',ascending=False)

In [77]:
regression_(dfx,y)

                  R_square           MSE           MAE
ExtraTree         0.999995    144.391055      5.559674
DecisionTree      0.999995    144.391055      5.559674
XGB               0.999235   1843.470023   1303.084058
GradientBoosting  0.956587  13885.725161  10369.728108
LinearRegressor   0.936452  16799.889827  12005.464624
Lasso             0.936304  16819.490639  12020.834633
Ridge             0.935083  16979.963146  12138.715647
ElasticNet        0.872844  23764.267566  16713.781815
KNeighbors        0.836076  26982.228340  18445.664196